# Load other aliases
if [ -f ~/.bash_aliases_git ]; then
  . ~/.bash_aliases_git
fi
if [ -f ~/.bash_aliases_docker ]; then
 . ~/.bash_aliases_docker
fi

# Always list hidden files
alias ls="ls -A --color"

# Make and change to directory
mkcd(){ mkdir -p -- "$1" && cd -P -- "$1"; }

# Fast change directories
alias ..="cd .."
alias ...="cd ../.."

# Find files with name
alias fn="find . -name $1"
